- id: validate-filename
  name: validate filename
  description: Hook ensures that TeX filenames are correct
  entry: lgh-validate-filename
  language: python
  types: [file, tex]
- id: check-latex-packages
  name: checks LaTeX packages
  description: Hook for checking LaTeX package imports
  entry: lgh-check-latex-packages
  language: python
  types: [file, tex]